#!/bin/bash

# Quick Deployment Script for PDF Genius
echo "🚀 PDF Genius Quick Deployment"
echo "=============================="

# Create Railway project
echo "1. Install Railway CLI:"
echo "   npm install -g @railway/cli"
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. Create new project:"
echo "   railway init"
echo "   (Choose 'Create new project', name: pdf-genius)"
echo ""
echo "4. Add PostgreSQL:"
echo "   railway add postgresql"
echo ""
echo "5. Add Redis:"
echo "   railway add redis"
echo ""
echo "6. Set environment variables:"
echo "   railway variables set GROQ_API_KEY='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'"
echo "   railway variables set PDF_CO_API_KEY='surendar.ai.pro@gmail.com_CHUtz4sGlMKf3xhKHjGwkfUzSE06V9Rup5z794lmsnO22AAYCZDnCDLDSHr96bWf'"
echo "   railway variables set SECRET_KEY='$(openssl rand -hex 32)'"
echo ""
echo "7. Deploy:"
echo "   railway up"
echo ""
echo "8. Get your URL:"
echo "   railway status"
echo ""
echo "⏱️  Time: 15 minutes"
echo "💰 Cost: Free"
echo "🌐 URL: https://pdf-genius.up.railway.app"
echo ""
echo "📱 Test immediately:"
echo "1. Visit your URL"
echo "2. Register account"
echo "3. Upload PDF"
echo "4. Try AI chat"
echo "5. Convert to Word"
echo ""
echo "🎯 Start earning tomorrow:"
echo "• Product Hunt launch"
echo "• First $29 customer"
echo "• $100-500 MRR in week 1"
echo ""
echo "🚀 Ready? Start with step 1!"