[build]
  command = "cd frontend && CI=false npm install --legacy-peer-deps && npm run build"
  publish = "frontend/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://pdf-genius.netlify.app/.netlify/functions"
  NEXT_PUBLIC_SITE_URL = "https://pdf-genius.netlify.app"